// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAL6lbfoEMSNuFY0aDGwBdbZ9OqMwqTw',
    appId: '1:267715483986:web:de947087c71f8c56f4828b',
    messagingSenderId: '267715483986',
    projectId: 'batch-13-6c6e1',
    authDomain: 'batch-13-6c6e1.firebaseapp.com',
    storageBucket: 'batch-13-6c6e1.firebasestorage.app',
    measurementId: 'G-BGH7ZQBW5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmfslL2CP31iTu2sSoUV3LPyqB6WfThUg',
    appId: '1:267715483986:android:aedeaedf54d542fcf4828b',
    messagingSenderId: '267715483986',
    projectId: 'batch-13-6c6e1',
    storageBucket: 'batch-13-6c6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-JZ3EU_tcOs09IwnrWv6Ye20yESjr5c',
    appId: '1:267715483986:ios:1aebbebab6cbb5c2f4828b',
    messagingSenderId: '267715483986',
    projectId: 'batch-13-6c6e1',
    storageBucket: 'batch-13-6c6e1.firebasestorage.app',
    iosBundleId: 'com.example.flutter13Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj-JZ3EU_tcOs09IwnrWv6Ye20yESjr5c',
    appId: '1:267715483986:ios:1aebbebab6cbb5c2f4828b',
    messagingSenderId: '267715483986',
    projectId: 'batch-13-6c6e1',
    storageBucket: 'batch-13-6c6e1.firebasestorage.app',
    iosBundleId: 'com.example.flutter13Firebase',
  );
}
